app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

not_found:
    pattern: /{not_found_string}
    requirements:
        not_found_string:  .+